### ISSUE TITLE
OutOfMemoryException when using ashx connector

### ISSUE THREAD

**Issue by amyth91** [servocoder/RichFilemanager#313]
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [Wiki](https://github.com/servocoder/RichFilemanager/wiki). Especially [deploy](https://github.com/servocoder/RichFilemanager/wiki/Deploy-and-setup) and [configuration](https://github.com/servocoder/RichFilemanager/wiki/Configuration-options) articles.
- [ ] I have checked that the bug I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I realise that server-side connectors are provided by various contributors. The implementations are vary due to programming language features/limitations or other factors. Thus a particular connector may not implement, or partially implement, the [API](https://github.com/servocoder/RichFilemanager/wiki/API) features.
- [x] I realise that any changes in configuration options and/or plugin parameters affect the plugin behavior. I specified all the differences from defaults in details.

**I use the following server-side connector (check one):**

- [ ] PHP connector by **servocoder**
- [ ] Java connector by **fabriceci**
- [ ] Python3 Flask connector by **jsooter**
- [ ] Python3 Flask connector by **stevelittlefish**
- [ ] NodeJs connector by **jlaustill** and **forestlake**
- [ ] ASP.NET Core connector by **sinanbozkus**
- [x] ASHX connector by **richeflits**
- [ ] Other (specified below)

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

I am getting an outofmemory exception when using ashx connector.

This is only happening on the live server and not on localhost. Any ideas ?

Below are the details from event log.

Exception information: 
    Exception type: OutOfMemoryException 
    Exception message: Out of memory.
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at filemanager.getFileInfo(FileInfo fileInfo, String path) in <server path>\Filemanager\connectors\ashx\filemanager.ashx:line 155
   at filemanager.getInfo(String path) in <server path>\Filemanager\connectors\ashx\filemanager.ashx:line 81
   at filemanager.ProcessRequest(HttpContext context) in <server path>\Filemanager\connectors\ashx\filemanager.ashx:line 384
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by amyth91** [comment]
This issue is resolved: The issue was due to a corrupt jpg file.
