### ISSUE TITLE
Function not found: imagecreatetruecolor when upload image

### ISSUE THREAD

**Issue by vgiotsas** [servocoder/RichFilemanager#67]
When I upload an image the generation of the thumbnail fails, although the image is being successfully uploaded. I checked the apache error log and I got the following error:

```
[:error] [pid 7456] [client 132.249.64.203:60411] Function not found: imagecreatetruecolor
[:error] [pid 7456] [client 132.249.64.203:60411] PHP Warning:  fopen(/var/www/html/RichFilemanager/userfiles/_thumbs/papers/DSC_1054.JPG): failed to open stream
[:error] [pid 7456] [client 132.249.64.203:60411] PHP Fatal error:  Uncaught exception 'Exception' with message 'Cannot open specified file for reading.' in /var/www/html/RichFilemanager/connectors/php/BaseFilemanager.php:544\nStack trace:\n#0 /var/www/html/RichFilemanager/connectors/php/LocalFilemanager.php(726): BaseFilemanager::get_real_filesize('/var/www/html/R...')\n#1 /var/www/html/RichFilemanager/connectors/php/BaseFilemanager.php(276): LocalFilemanager->actionGetImage(true)\n#2 /var/www/html/RichFilemanager/connectors/php/filemanager.php(48): BaseFilemanager->handleRequest()\n#3 {main}\n  thrown in /var/www/html/RichFilemanager/connectors/php/BaseFilemanager.php on line 544, referer: http://54.91.204.187/RichFilemanager/
```

**Comment by servocoder** [comment]
you have to install GD extension for PHP

**Comment by peterrotich** [comment]
I did install extension for PHP and it works perfectly.
